// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMUAQffr9kTU1aEbZI6V36IKk8A0Qwvfc',
    appId: '1:828889808530:web:1d70ee1d77eda6725ab04b',
    messagingSenderId: '828889808530',
    projectId: 'myfire-eaa07',
    authDomain: 'myfire-eaa07.firebaseapp.com',
    storageBucket: 'myfire-eaa07.appspot.com',
    measurementId: 'G-TB6VWZSN5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCayO55mHcEJ-McIeWR0Mk1UqMH7YcmHjA',
    appId: '1:828889808530:android:5c14ca72c8349a4c5ab04b',
    messagingSenderId: '828889808530',
    projectId: 'myfire-eaa07',
    storageBucket: 'myfire-eaa07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF8jl6_cq2srndhJsFjecfZNiykvIEqzQ',
    appId: '1:828889808530:ios:5043e5dfc2dae7515ab04b',
    messagingSenderId: '828889808530',
    projectId: 'myfire-eaa07',
    storageBucket: 'myfire-eaa07.appspot.com',
    iosBundleId: 'com.example.firebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF8jl6_cq2srndhJsFjecfZNiykvIEqzQ',
    appId: '1:828889808530:ios:abb99c4363469be25ab04b',
    messagingSenderId: '828889808530',
    projectId: 'myfire-eaa07',
    storageBucket: 'myfire-eaa07.appspot.com',
    iosBundleId: 'com.example.firebas.RunnerTests',
  );
}
